set default-bg               "#000000"
set default-fg               "#ffe1ba"
set statusbar-bg             "#141414"
set statusbar-fg             "#ffffff"
set inputbar-bg              "#141414"
set inputbar-fg              "#ffffff"
set notification-bg          "#141414"
set notification-fg          "#ffffff"
set notification-error-bg    "#141414"
set notification-error-fg    "#d08770"
set notification-warning-bg  "#141414"
set notification-warning-fg  "#cbaf89"
set completion-bg            "#141414"
set completion-fg            "#f2ede3"
set completion-highlight-bg  "#3b2908"
set completion-highlight-fg  "#fffaf2"
set recolor-darkcolor        "#000000"
set recolor-lightcolor       "#ffe1ba"
set completion-group-bg      "#1a1a1a"
set completion-group-fg      "#cbaf89"
set index-bg                 "#000000"
set index-fg                 "#ffe1ba"
set index-active-bg          "#ffe1ba"
set index-active-fg          "#141414"
set render-loading-bg        "#000000"
set render-loading-fg        "#ffe1ba"
set highlight-color          rgba(203,175,137,0.35)
set highlight-fg             rgba(255,250,242,0.95)
set highlight-active-color   rgba(152,127,91,0.45)
