# https://www.mapcoordinates.net/en
# long, lat of Central jakarta

### Matrouh
# latitude = 31.353
# longitude = 27.232

### Alexandria
latitude = 31.205753
longitude = 29.924526

madhab = "Shafi"
method = "Egyptian"
