# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#82aaff" }

syntect_theme = "~/.config/yazi/tmtheme.xml"

# Find
find_keyword  = { fg = "#ff757f", bold = true, italic = true, underline = true }
find_position = { fg = "#c099ff", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut      = { fg = "#ffc777", bg = "#ff757f" }
marker_marked   = { fg = "#82aaff", bg = "#86e1fc" }
marker_selected = { fg = "#ffc777", bg = "#ffc777" }

# Count
count_copied   = { fg = "#1a1b26", bg = "#c3e88d" }
count_cut      = { fg = "#1a1b26", bg = "#ffc777" }
count_selected = { fg = "#1a1b26", bg = "#82aaff" }

# Border
border_symbol = "│"
border_style  = { fg = "#589ed7" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#292e42", bg = "#82aaff", bold = true }
inactive = { fg = "#82aaff", bg = "#292e42" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#292e42", bg = "#82aaff", bold = true }
normal_alt  = { fg = "#82aaff", bg = "#292e42" }

# Select mode
select_main = { fg = "#292e42", bg = "#c3e88d", bold = true }
select_alt  = { fg = "#82aaff", bg = "#292e42" }

# Unset mode
unset_main = { fg = "#292e42", bg = "#c099ff", bold = true }
unset_alt  = { fg = "#82aaff", bg = "#292e42" }

# : }}}


# : Status bar {{{

[status]
overall = { fg = "#82aaff" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }


# Progress
progress_label = { fg = "#c8d3f5", bold = true }
progress_normal = { fg = "#82aaff", bg = "#292e42" }
progress_error = { fg = "#ff757f", bg = "#292e42" }

# Permissions
perm_sep   = { fg = "#82aaff" }
perm_type  = { fg = "#c3e88d" }
perm_read  = { fg = "#ffc777" }
perm_write = { fg = "#ff757f" }
perm_exec  = { fg = "#c099ff" }


# : }}}

# : Pick {{{

[pick]
border = { fg = "#82aaff" }
active = { fg = "#c099ff", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#82aaff" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#82aaff" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#82aaff" }
title   = {}
hovered = { fg = "#c099ff", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#292e42" }
cand            = { fg = "#86e1fc" }
rest            = { fg = "#82aaff" }
desc            = { fg = "#c099ff" }
separator       = "  "
separator_style = { fg = "#636da6" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#c3e88d" }
run     = { fg = "#c099ff" }
desc    = { fg = "#86e1fc" }
hovered = { bg = "#2f334d" }
footer  = { fg = "#c8d3f5", bg = "#222436" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#82aaff" }
title    = { fg = "#82aaff" }
tbl_col  = { fg = "#c3e88d" }
tbl_cell = { fg = "#c099ff", bg = "#292e42" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#c3e88d" }
title_warn  = { fg = "#ff757f" }
title_error = { fg = "#ffc777" }

# : }}}


# : Indicator {{{

[indicator]
padding = { open = "█", close = "█" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#ffc777" },

	# Media
	{ mime = "video/*", fg = "#c099ff" },
	{ mime = "audio/*", fg = "#c099ff" },

	# Archives
	{ mime = "application/zip",             fg = "#ff757f" },
	{ mime = "application/x-tar",           fg = "#ff757f" },
	{ mime = "application/x-bzip*",         fg = "#ff757f" },
	{ mime = "application/x-bzip2",         fg = "#ff757f" },
	{ mime = "application/x-7z-compressed", fg = "#ff757f" },
	{ mime = "application/x-rar",           fg = "#ff757f" },
	{ mime = "application/x-xz",            fg = "#ff757f" },

	# Documents
	{ mime = "application/doc",        fg = "#86e1fc" },
	{ mime = "application/epub+zip",   fg = "#86e1fc" },
	{ mime = "application/pdf",        fg = "#86e1fc" },
	{ mime = "application/rtf",        fg = "#86e1fc" },
	{ mime = "application/vnd.*",      fg = "#86e1fc" },

  # Special files
  { mime = "*", is = "orphan", fg = "#f29cb4", bg = "#93000a" },
  { mime = "application/*exec*", fg = "#ff757f" },

	# Fallback
	{ url = "*", fg = "#c8d3f5" },
	{ url = "*/", fg = "#82aaff" },
]

# : }}}
