#!/usr/bin/bash

case $1 in
shutdown)
  shutdown now
  ;;
reboot)
  reboot
  ;;
logout)
  hyprctl dispatch 'hl.dsp.exit()'
  ;;
suspend)
  systemctl suspend
  ;;
hibernate)
  systemctl hibernate
  ;;
lock)
  hyprlock --no-fade-in --immediate-render
  ;;
*)
  echo "error"
  ;;
esac
